### ISSUE TITLE
Disabling the entire World channel

### ISSUE THREAD

**Issue by ghost** [Orukxu/SpamThrottle#3]
For me after adding new keywords like W_o_W.com in this case result in the entire World channel being blocked. Only way to make text visible again is to add it too the channel whitelist which of course means I see the gold sellers as well.

**Comment by ghost** [comment]
Nevermind I woke upe way too early all I had to do was /reload.
Thank you for a working ST, needed badly now :)

**Comment by Orukxu** [comment]
No problem!
